### ISSUE TITLE
Misleading claims in README

### ISSUE THREAD

**Issue by fingolfin** [eschnett/CxxInterface.jl#1]
Your README begins with the claim
> Successor of Cxx.jl and CxxWrap.jl.

This is arguably false, as it comes with the implict connotation that it is an "official" succcessor (which it isn't) and that those projects are dead (which they are not, at least CxxWrap is actively used and receiving fixes).  

It certainly is an *alternative* to these packages, so you could say that.

You also claim CxxWrap does not support Julia 1.7. This is also not true, we are actively using it there. Of course there may be bugs, in that case; in that case an issue report would be good, otherwise the issue cannot be addressed

**Comment by eschnett** [comment]
Apologies; I've updated the README. Please let me know if I should make more corrections.

Regarding `CxxWrap.jl`, please see <https://github.com/JuliaInterop/libcxxwrap-julia/issues/90>.

**Comment by fingolfin** [comment]
Thank you. I'll take a peek at your cxxwrap issue.
